url: http://artistryhub.github.io/
baseurl: /ArtistryHub

# Site settings
title: Artistry Hub
email: artistryhub0@gmail.com
description: "Whether you want a DJ for your party or a band for a memorable event, our platform offers it all. ArtistryHub connects local performers to event organizers who are looking to take their events to the next level."


# Team names, titles and social links
people:
- name: Vlad Cătănoiu
  pic: 0
  position: Product Manager
  email: vlad.catanoiu@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/vladcatanoiu/
    - title: github
      url: https://github.com/vladalex01

- name: Andrei Șoșea
  pic: 1
  position: Marketing & PR Manager
  email: andrei_dorin.sosea@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/andrei-dorin-sosea/
    - title: github
      url: https://github.com/sosea

- name: Mihai Papa
  pic: 2
  position: Software Engineer
  email: mihai_eugen.papa@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mihai-eugen-papa-829084181/
    - title: github
      url: https://github.com/mihaipapa

- name: David Radu
  pic: 3
  position: UI/UX Developer
  email: david.radu0905@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/david-alexandru-radu-932009173
    - title: github
      url: https://github.com/alexradu07

- name: Maria Andreescu
  pic: 4
  position: Software Engineer
  email: maria.andreescu@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/maria-elena-andreescu/
    - title: github
      url: https://github.com/mariaandreescu

- name: Mihai Buică
  pic: 5
  position: Sales & Financial Manager
  email: mihai.buica@stud.acs.upb.ro
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mihai-buica/
    - title: github
      url: https://github.com/MihaiBuica

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: instagram
  #   url: #
  - title: github
    url: https://github.com/ArtistryHub/ArtistryHub

# Postal address (add as many lines as necessary)
address:
  - line: ACS, UPB
  - line: Bucharest, Romania

# Build settings
markdown: kramdown
permalink: pretty